#!/usr/bin/env bash
# Rainier MI355x runtime overrides for AMD Tinker (single-node).
# Usage: source examples/train/amd/run_rainier_env.sh
export VLLM_ENABLE_V1_MULTIPROCESSING="${VLLM_ENABLE_V1_MULTIPROCESSING:-0}"
export VLLM_USE_V1="${VLLM_USE_V1:-1}"
export INFERENCE_DISTRIBUTED_EXECUTOR_BACKEND="${INFERENCE_DISTRIBUTED_EXECUTOR_BACKEND:-mp}"
export INFERENCE_MAX_MODEL_LEN="${INFERENCE_MAX_MODEL_LEN:-4096}"
export INFERENCE_MAX_NUM_BATCHED_TOKENS="${INFERENCE_MAX_NUM_BATCHED_TOKENS:-8192}"
export INFERENCE_MAX_NUM_SEQS="${INFERENCE_MAX_NUM_SEQS:-64}"
export INFERENCE_GPU_MEMORY_UTILIZATION="${INFERENCE_GPU_MEMORY_UTILIZATION:-0.5}"
